apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: shakee-ns
spec:
  replicas: 5   # <-- Correct placement
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
